name: First Action

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: npm install
      - name: Stop running container
        run: docker stop my-container
      - name: Remove running container
        run: docker container rm api-image
      - name: Build Image
        run: docker build --tag api-image .
      - name: Run Image
        run: docker run -p 3000:3000 --name api-container my-image
