name: First Action

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: Install dependencies
        run: npm install
        continue-on-error: true
      - name: Stop running container
        run: docker stop api-container
        continue-on-error: true
      - name: Remove running container
        run: docker rm api-container
        continue-on-error: true
      - name: Remove image
        run: docker rmi api-image
        continue-on-error: true
      - name: Build Image
        run: docker build --tag api-image .
      - name: Run Image
        run: docker run --name api-container -d api-image -p 8480:3000
